//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Visualizer_X.rc
//
#define IDC_RESET                       2
#define ID_COMPUTE                      2
#define IDC_VIEWRESET                   3
#define ID_BROWSE_READ                  3
#define ID_BROWSE_SCRIPT                4
#define ID_BROWSE_TEMPLATE              5
#define ID_BROWSE_EXPORTDIR             6
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_FRAME              101
#define IDD_PROPPAGE_SETTINGS_PARTICLES 102
#define IDB_SPLASH                      103
#define IDR_MAINFRAME                   128
#define IDR_VISUALTYPE                  129
#define IDD_LIGHT_DIALOG                130
#define IDD_MATERIALS_DIALOG            131
#define IDR_MATERIALS                   135
#define IDD_PROJECTION_DIALOG           137
#define IDD_PARTICLE_DIALOG             138
#define IDD_REGION_DIALOG               139
#define IDD_SETTINGS_DIALOG             140
#define IDD_VIEWPARTICLE_DIALOG         143
#define IDD_CLUSTER_DIALOG              144
#define IDD_CELLS_DIALOG                146
#define IDD_READ_DIALOG                 147
#define IDD_CURRENT_DIALOG              148
#define IDD_OBJECT_DIALOG               149
#define IDD_RDF_DIALOG                  152
#define IDR_FORMAT_TOOLBAR              158
#define IDR_RDF                         160
#define IDD_FORMAT_DIALOG               161
#define IDD_BOD_DIALOG                  162
#define IDD_HELP_DIALOG                 164
#define IDD_DIALOG_CHANGETYPE           166
#define IDR_MENU_CONTEXT                168
#define IDD_DIFFRACTION_DIALOG          169
#define IDI_DIFFRACTION                 171
#define IDD_ADDOBJ_DIALOG               172
#define IDD_PROPPAGE_SETTINGS_EFFECTS   173
#define IDD_PROPPAGE_SETTINGS_PREPROC   174
#define IDD_REPLICATE_DIALOG            175
#define IDC_SLIDER_AMBIENT_RED          1001
#define IDC_LIGHT_POS_X                 1002
#define IDC_SLIDER_AMBIENT_GREEN        1003
#define IDC_VIEW_XANGLE                 1003
#define IDC_SLIDER_AMBIENT_BLUE         1004
#define IDC_VIEW_YANGLE                 1004
#define IDC_SLIDER_DIFFUSE_RED          1005
#define IDC_VIEW_ZANGLE                 1005
#define IDC_SLIDER_DIFFUSE_GREEN        1006
#define IDC_VIEW_LEFT                   1006
#define IDC_SLIDER_DIFFUSE_BLUE         1007
#define IDC_VIEW_RIGHT                  1007
#define IDC_SLIDER_SPECULAR_RED         1008
#define IDC_VIEW_TOP                    1008
#define IDC_SLIDER_SPECULAR_GREEN       1009
#define IDC_VIEW_BOTTOM                 1009
#define IDC_SLIDER_SPECULAR_BLUE        1010
#define IDC_VIEW_NEAR                   1010
#define IDC_SLIDER_EMISSION_RED         1011
#define IDC_VIEW_FAR                    1011
#define IDC_CHECK_POINT_SRC             1012
#define IDC_SLIDER_EMISSION_GREEN       1012
#define IDC_VIEW_TRANSLATE              1012
#define IDC_SLIDER_AMBIENT_ALPHA        1013
#define IDC_VIEW_SCALE                  1013
#define IDC_LIGHT_POS_Y                 1014
#define IDC_SLIDER_EMISSION_BLUE        1014
#define IDC_LIGHT_XANGLE                1014
#define IDC_LIGHT_POS_Z                 1015
#define IDC_SLIDER_DIFFUSE_ALPHA        1015
#define IDC_LIGHT_YANGLE                1015
#define IDC_SHININESS                   1016
#define IDC_LIGHT_ZANGLE                1016
#define IDC_MATERIALS_TYPE              1017
#define IDC_COMBO_MATTYPE               1017
#define IDC_LIGHT_XPOS                  1017
#define IDC_LEFT                        1018
#define IDC_SLIDER_SPECULAR_ALPHA       1018
#define IDC_LIGHT_YPOS                  1018
#define IDC_RIGHT                       1019
#define IDC_SLIDER_EMISSION_ALPHA       1019
#define IDC_LIGHT_ZPOS                  1019
#define IDC_TOP                         1020
#define IDC_COMBO_COLOR                 1020
#define IDC_LIGHT_CONSTANT              1020
#define IDC_BOTTOM                      1021
#define IDC_LIGHT_LINEAR                1021
#define IDC_ORTHO                       1022
#define IDC_LIGHT_QUAD                  1022
#define IDC_FRUSTUM                     1023
#define IDC_NEAR                        1024
#define IDC_FAR                         1025
#define IDC_NUMBEADS_SKIPPED            1025
#define IDC_TRANSLATE                   1026
#define IDC_DEF_FILE                    1026
#define IDC_SCALE                       1027
#define IDC_LIST_FILE_DESCR             1027
#define IDC_NUMOBJSPERPARTICLE          1027
#define IDC_STATIC_FILENAME             1028
#define IDC_CENTER                      1029
#define IDC_NUMBEADS                    1029
#define IDC_STATIC_SCRIPT               1029
#define IDC_STARTIDX                    1029
#define IDC_LX                          1030
#define IDC_PARTICLESCALESTEP           1030
#define IDC_STATIC_TEMPLATE             1030
#define IDC_OBJSCALE                    1030
#define IDC_LY                          1031
#define IDC_ROTATESTEP                  1031
#define IDC_NUMBEADSPERPARTICLE         1031
#define IDC_LZ                          1032
#define IDC_PARTICLETRANSLATESTEP       1032
#define IDC_LOCALINDICES                1032
#define IDC_CHECK_XROTATE               1033
#define IDC_CENTER_SPHERE               1033
#define IDC_CHECK_YROTATE               1034
#define IDC_RADIUS                      1034
#define IDC_RADIUS_INNER                1034
#define IDC_CHECK_ZROTATE               1035
#define IDC_RADIUS_OUTER                1035
#define IDC_XMODELANGLE                 1036
#define IDC_YMODELANGLE                 1037
#define IDC_ZMODELANGLE                 1038
#define IDC_CHECK_TWOLIGHTSRC           1039
#define IDC_CHECK_BLEND                 1040
#define IDC_COMBO_DIR                   1041
#define IDC_CHECK_OVERRIDENUMBEADS      1042
#define IDC_CHECK_APPLYCOMMAND          1042
#define IDC_EDIT_INDEX_START            1043
#define IDC_RESOLUTION                  1043
#define IDC_CHECK_RELEASEPBC            1043
#define IDC_EDIT_INDEX_END              1044
#define IDC_EDIT_CUTOFF                 1044
#define IDC_CHECK_FOGGING               1044
#define IDC_CHECK_PBC                   1045
#define IDC_FOGDENSITY                  1045
#define IDC_COMBO_TYPE                  1046
#define IDC_COMBO_FOGMODE               1046
#define IDC_DIV_X                       1047
#define IDC_COMBO_DIM                   1047
#define IDC_FOG_NEAR                    1047
#define IDC_DIV_Y                       1048
#define IDC_FOG_FAR                     1048
#define IDC_DIV_Z                       1049
#define IDC_CHECK_OUTLINE               1049
#define IDC_OUTLINEWIDTH                1050
#define IDC_CHECK_EXPORTBMP             1051
#define IDC_OBJECTSCALE                 1051
#define IDC_CHECK_USETEMPLATE           1052
#define IDC_PARTICLESCALESTEP2          1052
#define IDC_PARTICLE_SCALE              1053
#define IDC_ROTATESTEP2                 1053
#define IDC_UPDATE                      1054
#define IDC_PARTICLETRANSLATESTEP2      1054
#define IDC_STARTING_FRAME              1055
#define IDC_EDIT_WORKINGDIR             1056
#define IDC_RADIO_VOLTYPE               1057
#define IDC_RADIO_VOLTYPE2              1058
#define IDC_CENTER_BOX                  1059
#define IDC_EDIT_RDFGRAPH               1062
#define IDC_EDIT_BINSIZE                1064
#define IDC_EDIT_LMAX                   1065
#define IDC_STATIC_TYPE                 1069
#define IDC_STATIC_BINSIZE              1070
#define IDC_STATIC_LMAX                 1071
#define IDC_LINEWIDTH                   1072
#define IDC_STATIC_XYPOS                1072
#define IDC_MAJORTICKX                  1073
#define IDC_CUTIN                       1073
#define IDC_MINORTICKX                  1074
#define IDC_CUTOUT                      1074
#define IDC_MAJORTICKY                  1075
#define IDC_MAXPOINTS                   1075
#define IDC_MINORTICKY                  1076
#define IDC_WINDOWSIZE                  1076
#define IDC_FONTSIZE                    1077
#define IDC_MINX                        1078
#define IDC_CHECK_CURSOR                1079
#define IDC_MAXX                        1079
#define IDC_BUTTON_COLOR                1080
#define IDC_MINY                        1081
#define IDC_MAXY                        1082
#define IDC_COMBO_SRC                   1083
#define IDC_COMBO_DEST                  1084
#define IDC_CHECK_SWAP                  1085
#define IDC_CHECK_SHOWBONDS             1087
#define IDC_STATIC_STATUS               1088
#define IDC_EDIT_INDEX                  1089
#define IDC_SCROLL_BINSIZE              1090
#define IDC_STATIC_COORD                1091
#define IDC_STATIC_DIFF                 1093
#define IDC_EDIT_PEAKWIDTH              1094
#define IDC_EDIT_INTENSITY              1095
#define IDC_EDIT_ZOOM                   1096
#define IDC_STATIC_ZOOM                 1097
#define IDC_STATIC_INTENSITY            1098
#define IDC_STATIC_PEAKWIDTH            1099
#define IDC_STATIC_FFTSIZE              1100
#define IDC_COMBO_FFTSIZE               1101
#define IDC_HEADERLINES                 1102
#define IDC_CHECK_OUTSIDE               1103
#define IDC_SHIFTX                      1103
#define IDC_PARTICLE_MINSCALE           1104
#define IDC_SHIFTY                      1104
#define IDC_PARTICLE_MAXSCALE           1105
#define IDC_SHIFTZ                      1105
#define IDC_PARTICLE_SCALINGSTEP        1106
#define IDC_PARTICLE_SCALINGCOEFF       1106
#define IDC_NUMCOPIES                   1108
#define IDC_CHECK_USEPARTICLETYPE       1109
#define ID_VIEW_LIGHT                   32771
#define ID_VIEW_MATERIALS               32772
#define ID_TOGGLE_LIGHTSRC              32773
#define ID_VIEW_PROJECTION              32774
#define ID_ORTHO                        32775
#define ID_WINDOW_CLOSEALL              32778
#define ID_VIEW_BACKGROUND              32779
#define ID_FILE_USINGTEMPLATE           32780
#define ID_FILE_READ                    32781
#define ID_VIEW_SETREGION               32782
#define ID_VIEW_TYPE_TYPE2              32786
#define ID_VIEW_TYPE_TYPE3              32787
#define ID_VIEW_TYPE_TYPE4              32788
#define ID_VIEW_TYPE_TYPE5              32789
#define ID_VIEW_TYPE_TYPE6              32790
#define ID_VIEW_TYPE_ALL                32791
#define ID_VIEW_TYPE_TYPE1              32792
#define ID_VIEW_CHANGETYPE              32793
#define ID_FILE_WRITE                   32794
#define ID_EDIT_SETTINGS                32795
#define IDC_XY                          32796
#define IDC_YZ                          32797
#define IDC_ZX                          32798
#define ID_TOOLS_CLUSTERING             32800
#define ID_POSITIVE                     32801
#define ID_NEGATIVE                     32802
#define ID_VIEW_CELLS                   32803
#define ID_VIEW_PARTICLE                32804
#define ID_EDIT_EXPORT                  32805
#define ID_TOOLS_MOVETOORIGIN           32807
#define ID_VIEW_CURRENTPARAMETERS       32808
#define ID_XZ                           32809
#define ID_ZY                           32810
#define ID_YX                           32812
#define ID_FILE_WRITETOPOV              32813
#define ID_WINDOW_TILEVERTICALLY        32814
#define ID_TOOLS_ADDOBJECTS_FROMFILE    32817
#define ID_TOOLS_ADDOBJECTS_INDIVIDUALS 32818
#define ID_DRAWINGOBJS                  32820
#define ID_EDIT_EXPORTTOPOSTSCRIPT      32821
#define ID_FILE_LOADSTATE               32823
#define ID_TOOLS_RDF                    32824
#define ID_GRAPH_COPYTOCLIPBOARD        32826
#define ID_FORMAT_SERIES                32827
#define ID_FORMAT_GRIDLINES             32828
#define ID_BOD                          32830
#define ID_TOOLS_BOD                    32831
#define ID_DRAWORIGIN                   32833
#define ID_HELP_USERSGUIDE              32834
#define ID_TOOLS_CHANGETYPE             32835
#define ID_FORMAT_SAVE                  32841
#define ID_PICKING_MODE                 32842
#define ID_FILE_WRITETOPOS              32847
#define ID_TOOLS_DIFFRACTION            32848
#define ID_TOOLS_REPLICATE              32849
#define ID_HELP_TEMPLATEFILEFORMAT      32850
#define IDC_CHECK_SQ					32851
#define IDC_REP_X						32852
#define IDC_REP_Y						32853
#define IDC_REP_Z						32854

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32851
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
